### ISSUE TITLE
Release Gnocchi Version 0.1.0

### ISSUE THREAD

**Issue by tkdagdelen** [bigdatagenomics/gnocchi#24]
Release of Gnocchi with basic functionality. This includes: 

- linear regression
- logistic reg
- MAF
- mind
- geno
- phenotype loading with and without covariates
- all of the above with incremental model saving, loading, and updating

**Todo:** 

Cleanup #25
- [ ] Strip functionality that will not be in 0.1.0 
- [ ] Clean out unnecessary comments etc. 
- [ ] Add documentation
- [ ] Add thorough readme

Testing #26
- [ ] Review of all test suites and addition of additional rigorous unit tests as needed
- [ ] End-to-end test on reputable data

Dependency/Build Cleanup #27 
- [ ] Update Spark and ADAM

Code Review and Improvement
- [ ] Code Review of all code (readability, conciseness, run-time)
- [ ] Run-time optimization (changing for's in run-time critical code to while, as well as refactoring if necessary)
